### ISSUE TITLE
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

### ISSUE THREAD

**Issue by Marcus1996-dot** [narrowsnap/pytorch_STN#1]
Thanks for you great code! but,when i run you code ,a error above occured and i couldn't resolve it.could you please help me? Thanks in advance.
![image](https://user-images.githubusercontent.com/53923029/67934513-0033b180-fc03-11e9-8954-102998d84cfa.png)

**Comment by narrowsnap** [comment]
It may caused by version of cuda or torch.
Here is my system information:
`cuda: 9.0`
`cudnn: 7`
`torch: 0.4.1`

I'll release a docker image which can run this code later.

**Comment by narrowsnap** [comment]
@Marcus1996-dot I added docker usage. You can see it in docker/README.md.

**Comment by Marcus1996-dot** [comment]
@narrowsnap ,Thanks a lot.the problem is the version of cuda.Thanks for you kindly help.
